import asyncio
from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeoutError

async def fetch_youtube_cookies():
    print("[Playwright] Starting browser to fetch YouTube cookies...")
    async with async_playwright() as p:
        # Launch chromium with arguments to reduce detection and optimize for VPS
        browser = await p.chromium.launch(
            headless=True,
            args=[
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--disable-dev-shm-usage",
                "--disable-blink-features=AutomationControlled",
                "--mute-audio",
                "--disable-extensions",
                "--disable-gpu",
                "--single-process",        # Runs renderer and browser in same process to save RAM (critical for 512MB)
                "--disable-software-rasterizer",
                "--disable-background-networking",
                "--disable-default-apps",
                "--disable-sync",
                "--renderer-process-limit=1",
            ]
        )
        
        # Create a context with a realistic user agent
        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            viewport={"width": 1280, "height": 720},
            locale="en-US",
            timezone_id="America/New_York"
        )
        
        # Inject CONSENT cookie to bypass the European cookie consent dialog
        await context.add_cookies([{
            "name": "CONSENT",
            "value": "YES+cb",
            "domain": ".youtube.com",
            "path": "/",
        }])
        
        page = await context.new_page()
        
        # Temporarily allowing all resources so we can see the screenshot clearly
        async def route_intercept(route):
            if route.request.resource_type in ["media"]:
                await route.abort()
            else:
                await route.continue_()
                
        await page.route("**/*", route_intercept)
        
        # Remove webdriver flag to evade basic bot detection
        await page.add_init_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")

        print("[Playwright] Navigating to YouTube...")
        try:
            # Navigate to the YouTube homepage (takes less RAM than a video page)
            await page.goto("https://www.youtube.com/", wait_until="domcontentloaded", timeout=30000)
            
            print("[Playwright] Waiting for main app to load...")
            # Wait for the main YouTube app container to load
            await page.wait_for_selector("ytd-app", timeout=15000)
            
            # Wait a small extra time to ensure background JS (like logging analytics/cookies) finishes
            await page.wait_for_timeout(3000)
            
        except PlaywrightTimeoutError:
            print("[Playwright] Timeout while loading page, but will attempt to extract cookies anyway...")
        except Exception as e:
            print(f"[Playwright] Error during navigation: {e}")

        print("[Playwright] Extracting cookies...")
        cookies = await context.cookies()
        
        print("[Playwright] Taking screenshot for debugging...")
        try:
            await page.screenshot(path="screenshot.png", full_page=True)
            print("[Playwright] Screenshot saved to screenshot.png")
        except Exception as e:
            print(f"[Playwright] Failed to take screenshot: {e}")
            
        await browser.close()
        
        if not cookies:
            print("[Playwright] Warning: No cookies were found!")
            return

        # Save cookies in Netscape format (which yt-dlp expects)
        with open("cookies.txt", "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# https://curl.haxx.se/rfc/cookie_spec.html\n")
            f.write("# This file is generated by Playwright!\n\n")
            for cookie in cookies:
                domain = cookie["domain"]
                include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
                path = cookie["path"]
                secure = "TRUE" if cookie["secure"] else "FALSE"
                
                # Format expiration time correctly for Netscape format
                expires = cookie.get("expires", 0)
                expires_str = str(int(expires)) if expires > 0 else "0"
                
                name = cookie["name"]
                value = cookie["value"]
                
                f.write(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires_str}\t{name}\t{value}\n")
                
        print(f"[Playwright] Successfully saved {len(cookies)} cookies to cookies.txt!")

if __name__ == "__main__":
    asyncio.run(fetch_youtube_cookies())
